export const PROFILE_INFO_FORM_SET_VALUE = 'PROFILE_INFO_FORM_SET_VALUE';
export const PROFILE_INFO_FORM_SUBMIT = 'PROFILE_INFO_FORM_SUBMIT';
export const PROFILE_INFO_FORM_SUBMIT_SUCCESS = 'PROFILE_INFO_FORM_SUBMIT_SUCCESS';
export const PROFILE_INFO_FORM_SUBMIT_FAILED = 'PROFILE_INFO_FORM_SUBMIT_FAILED';

export const setFormValue = (field, value) => ({
    type: PROFILE_INFO_FORM_SET_VALUE,
    field,
    value
});