export const USER_REGISTER_FORM_SET_VALUE = 'USER_REGISTER_FORM_SET_VALUE';
export const USER_REGISTER_FORM_SUBMIT = 'USER_REGISTER_FORM_SUBMIT';
export const USER_REGISTER_FORM_SUBMIT_SUCCESS = 'USER_REGISTER_FORM_SUBMIT_SUCCESS';
export const USER_REGISTER_FORM_SUBMIT_FAILED = 'USER_REGISTER_FORM_SUBMIT_FAILED';

export const setUserFormValue = (field, value) => ({
    type: USER_REGISTER_FORM_SET_VALUE,
    field,
    value
});