export const SET_USER_DATA = 'SET_USER_DATA';
export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';
export const DELETE_USER_DATA = 'DELETE_USER_DATA'